version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: thagkwar783
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"

  server:
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: thagkwar783
      DB_NAME: inputlinear_re
      DB_PORT: 3307

  app:
    build: ./project
    ports:
      - "4040:3000"
    depends_on:
      - server